
--KULLANICILARIN ÜLKE VS. BÝLGÝLERÝNÝ GETÝREN SORGU 
SELECT
U.NAMESURNAME,
C.COUNTRY,
CT.CITY,
T.TOWN,
D.DISTRICT,
A.ADDRESSTEXT
FROM USERS U 
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRIES C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.COUNTRYID=C.ID
JOIN TOWNS T ON T.CITYID=CT.ID
JOIN DISTRICTS D ON D.TOWNID=T.ID
