
--KULLANICILARIN TOPLAM SATIÞ MÝKTARIAN GÖRE SIRALAMASI
SELECT
U.NAMESURNAME,
SUM(O.TOTALPRICE) AS TOPLAM_SATIÞ_MÝKTARI
FROM USERS U 
JOIN ORDERS O ON U.ID=O.USERID
GROUP BY U.NAMESURNAME
ORDER BY SUM(O.TOTALPRICE) DESC