CREATE TABLE ADDRESS(
ID INT IDENTITY(1,1) PRIMARY KEY,
ADDRESSTEXT VARCHAR(500) NOT NULL,
POSTALCODE VARCHAR(20) NOT NULL,
USERID INT NOT NULL,
CONSTRAINT FK_ADDRESS_USERS FOREIGN KEY (USERID) REFERENCES USERS(ID) ON DELETE CASCADE,
COUNTRYID INT NOT NULL,
CONSTRAINT FK_ADDRESS_COUNTRIES FOREIGN KEY(COUNTRYID) REFERENCES COUNTRIES(ID) ON DELETE CASCADE,
)