CREATE TABLE CITIES(
ID INT IDENTITY(1,1) PRIMARY KEY,
CITYNAME VARCHAR(100) NOT NULL,
COUNTRYID INT NOT NULL,
CONSTRAINT FK_CITIES_COUNTRIES  FOREIGN KEY(COUNTRYID) REFERENCES COUNTRIES(ID) ON DELETE CASCADE)
