CREATE TABLE DISTRICTS(
ID INT IDENTITY(1,1) PRIMARY KEY,
DISTRICTNAME VARCHAR(100) NOT NULL,
TOWN_ID INT NOT NULL,
CONSTRAINT FK_DISTRICTS_TOWNS FOREIGN KEY(TOWN_ID) REFERENCES TOWNS(ID)ON DELETE CASCADE)