CREATE TABLE INVOICES(
ID INT IDENTITY(1,1) PRIMARY KEY,
ADDRESSID INT NOT NULL,
CONSTRAINT FK_INVOICES_ADDRESS FOREIGN KEY (ADDRESSID) REFERENCES ADDRESS(ID),
ORDERID INT NOT NULL,
CONSTRAINT FK_INVOICES_ORDERS FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID),
CARGOFICHENO VARCHAR(100) NOT NULL,
DATE_ DATETIME ,
TOTALRPICE FLOAT)