CREATE TABLE ITEMS(
ID INT IDENTITY(1,1) PRIMARY KEY,
ITEMNAME VARCHAR(200) NOT NULL,
ITEMCODE VARCHAR(100) NOT NULL,
BRAND VARCHAR(100) NOT NULL,
UNITPRICE FLOAT NOT NULL,
CATEGORYID INT NOT NULL,
CONSTRAINT FK_ITEMS_CATEGORIES FOREIGN KEY(CATEGORYID) REFERENCES CATEGORIES(ID))