
CREATE TABLE ORDERDETAILS(
ID INT IDENTITY(1,1) PRIMARY KEY,
ITEMID INT NOT NULL,
CONSTRAINT FK_ORDERDETAILS_ITEMS FOREIGN KEY(ITEMID) REFERENCES ITEMS(ID),
ORDERID INT NOT NULL,
CONSTRAINT FK_ORDERDETAILS_ORDERS FOREIGN KEY(ORDERID) REFERENCES ORDERS(ID),
AMOUNT INT NOT NULL,
UNITPRICE FLOAT NOT NULL,
LINETOTAL FLOAT NOT NULL)