CREATE TABLE ORDERS(
ID INT IDENTITY(1,1) PRIMARY KEY,
STATUS BIT,
DATE_ DATETIME,
TOTALPRICE FLOAT,
USERID INT NOT NULL,
CONSTRAINT FK_ORDERS_USERS FOREIGN KEY (USERID) REFERENCES USERS(ID) ,
ADDRESSID INT NOT NULL,
CONSTRAINT FK_ORDERS_ADDRESS FOREIGN KEY(ADDRESSID) REFERENCES ADDRESS(ID) ,
)
