CREATE TABLE PAYMENTS(
ID INT IDENTITY(1,1) PRIMARY KEY,
IS_OK BIT,
PAYMENTTYPE VARCHAR(100),
DATE_ DATETIME ,
APPROVECODE VARCHAR(100) NOT NULL,
PAYMENTTOTAL FLOAT NOT NULL,
ORDERID INT NOT NULL,
CONSTRAINT FK_PAYMENTS_ORDERS FOREIGN KEY(ORDERID) REFERENCES ORDERS(ID))