CREATE TABLE SHIPMENTS(
ID INT IDENTITY(1,1) PRIMARY KEY,
SHIPMENT_FICHENO VARCHAR(100) NOT NULL,
ADDRESSID INT NOT NULL,
CONSTRAINT FK_SHIPMENTS_ADDRESS FOREIGN KEY(ADDRESSID) REFERENCES ADDRESS(ID),
ORDERID INT NOT NULL,
CONSTRAINT FK_SHIPMENTS_ORDERS FOREIGN KEY(ORDERID) REFERENCES ORDERS(ID) )