CREATE TABLE USERS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAMESURNAME VARCHAR(100),
USERNAME VARCHAR(100) NOT NULL UNIQUE,
PASSWORD VARCHAR(255) NOT NULL,
TC_NO VARCHAR(11) NOT NULL UNIQUE,
BIRTHDATE DATETIME NOT NULL,
GENDER BIT NOT NULL,
MAIL VARCHAR(100) NOT NULL UNIQUE,
PHONE_NO VARCHAR(10) NOT NULL UNIQUE,
CREATEDDATE DATETIME DEFAULT GETDATE())
